version: "3.9"
services:

  server:
    build: .
    container_name: "nodejsserver"
    ports:
      - "3000:3000"
    depends_on: 
      - database
    networks:
      databasenet:
        aliases:
            - databasenet-server

  database:
    image: "mysql:latest"
    container_name: database
    restart: always
    volumes: 
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: iot
    networks:
      databasenet:
        aliases:
            - databasenet-database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadminsrv
    depends_on: 
      - database
    environment:
      PMA_HOST: databasenet-database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8000:80"
    networks:
      databasenet:
        aliases:
            - databasenet-phpmyadmin

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3030:3000
    volumes:
      - /home/grafana:/var/lib/grafana
      - /home/certs:/certs
    environment:
      - HTTP_USER=admin
      - HTTP_PASS=password
      - MYSQLDB_HOST=database
      - MYSQLDB_PORT=3306
      - MYSQLDB_NAME=iot
      - MYSQLDB_USER=root
      - MYSQLDB_PASS=my-secret-pw
    restart: always
    networks:
      databasenet:
        aliases:
            - databasenet-grafana


volumes:
  data:

networks:
  databasenet: {}