version: "3.9"
services:
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on: 
      - database
  database:
    image: "mysql:latest"
    restart: always
    volumes: 
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadminsrv
    depends_on: 
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8080:80"
  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3030:3000"
    volumes:
      - grafana-storage:/var/lib/grafana grafana/grafana-enterprise
volumes:
  data:
  grafana-storage:
